"""
Plain-English narrative summary of a Biodiversity Gain Plan, generated by
Claude Haiku. Falls back to a minimal static summary if the API key is not
configured or the call fails.
"""
from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

MODEL = "claude-haiku-4-5"


def build_summary(doc: dict, route_result: dict) -> str:
    """
    Call Claude Haiku to produce a plain-English paragraph summarising the
    BNG report for a non-specialist audience.

    Args:
        doc: BGPDocument dict (fully built by builder.build_gain_plan)
        route_result: raw route calculation result from /api/route
    """
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        logger.warning("ANTHROPIC_API_KEY not set — skipping AI summary")
        return _fallback_summary(doc, route_result)

    try:
        import anthropic  # lazy import so the module loads without the package

        prompt = _build_prompt(doc, route_result)
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model=MODEL,
            max_tokens=512,
            messages=[{"role": "user", "content": prompt}],
        )
        summary = message.content[0].text.strip()
        logger.info("Claude summary generated (%d chars)", len(summary))
        return summary

    except Exception as e:
        logger.error("Claude summary failed: %s — using fallback", e)
        return _fallback_summary(doc, route_result)


# ── Prompt builder ─────────────────────────────────────────────────────────

def _build_prompt(doc: dict, route_result: dict) -> str:
    sections = doc["sections"]
    metric = sections["biodiversity_gain_metric"]
    pre_hab: list[dict] = sections["pre_development_habitat"]
    bbox: list[float] = sections["development_details"]["coordinates"].get("bbox_wgs84", [])
    segments: list[dict] = route_result.get("segments", [])
    total_length_m: float = route_result.get("total_length_m", 0.0)

    location = _location_label(bbox)
    length = _length_label(total_length_m)

    hab_lines = "\n".join(
        f"  - {r['habitat_type']}: {r['area_ha']:.4f} ha, "
        f"distinctiveness {r['distinctiveness']}, {r['units']:.4f} units"
        for r in pre_hab
    )

    awi_count = sum(1 for s in segments if s.get("ancient_woodland"))
    sssi = sections["sssi_consultation_required"]
    lnrs = sections["lnrs_areas_crossed"]

    constraints: list[str] = []
    if awi_count:
        constraints.append(f"{awi_count} segment(s) pass through Ancient Woodland")
    if sssi:
        constraints.append("route crosses an SSSI Impact Risk Zone")
    if lnrs:
        constraints.append(f"route crosses {len(lnrs)} LNRS priority area(s)")

    constraints_str = (
        "\n".join(f"  - {c}" for c in constraints) if constraints
        else "  None identified"
    )

    return f"""You are a biodiversity consultant writing for a planning officer who is not a
specialist. Write 3–4 clear, jargon-free sentences that summarise the
Biodiversity Gain Plan below. Explain what the route is, what the biodiversity
impact will be, what any deficit means practically (off-site compensation),
and call out any significant constraints in plain English. Do not use bullet
points or headers — write flowing prose only.

--- BNG REPORT DATA ---
Location: {location}
Route length: {length}
Reference: {doc['reference']}

Pre-development habitats:
{hab_lines}

Biodiversity Gain Metric:
  Pre-development units:  {metric['total_pre_units']:.2f}
  Post-development units: {metric['total_post_units']:.2f}
  Net change:             {metric['net_change_percent']:.1f}%
  Gain deficit:           {metric['gain_deficit']:.2f} units

Constraints:
{constraints_str}
--- END DATA ---"""


# ── Fallback ───────────────────────────────────────────────────────────────

def _fallback_summary(doc: dict, route_result: dict) -> str:
    """Minimal deterministic summary used when Claude is unavailable."""
    sections = doc["sections"]
    metric = sections["biodiversity_gain_metric"]
    total_length_m: float = route_result.get("total_length_m", 0.0)
    deficit = metric["gain_deficit"]
    pct = metric["net_change_percent"]

    length = _length_label(total_length_m)
    impact = (
        f"a net loss of {abs(pct):.1f}%, creating a shortfall of {deficit:.2f} units "
        f"that must be offset through statutory biodiversity compensation"
        if pct < 0
        else f"a net gain of {pct:.1f}%, meeting the statutory 10% requirement"
    )
    return (
        f"This {length} access road would result in {impact}. "
        f"Pre-development habitat value: {metric['total_pre_units']:.2f} units. "
        f"Post-development: {metric['total_post_units']:.2f} units. "
        f"See the detailed tables below for a full habitat breakdown."
    )


# ── Helpers ────────────────────────────────────────────────────────────────

def _location_label(bbox: list[float]) -> str:
    if len(bbox) < 4:
        return "the proposed development area"
    mid_lat = (bbox[1] + bbox[3]) / 2
    mid_lng = (bbox[0] + bbox[2]) / 2
    lng_dir = "E" if mid_lng >= 0 else "W"
    return f"{mid_lat:.3f}°N, {abs(mid_lng):.3f}°{lng_dir}"


def _length_label(length_m: float) -> str:
    if length_m >= 1000:
        return f"{length_m / 1000:.1f} km"
    return f"{round(length_m)} m"
